---

- name: Include OS sepcific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Disable Host Key Checking
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regex: "^#host_key_checking"
    line: "host_key_checking=False"

# - name: Set permissions
#   command: "chmod 0600 {{ item }}"
#   with_items:
#     - /root/.ssh/id_rsa
#     - /root/.ssh/ansible.pem