---

- name: Remove firewalld
  yum:
    name: firewalld
    state: absent

- name: Install ansible
  yum:
    name: "{{ packages }}"
    state: latest
  register: result
  retries: 10
  delay: 60
  until: result is succeeded
  vars:
    packages:
      - ansible
      - erlang
      - socat
      - rabbitmq-server


