---

- name: Update firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 4369
    - 25672
    - 15672

- name: Allow xinetd to listen on tcp port
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items:
    - 4369
    - 25672
    - 15672

- name: Install ansible
  yum:
    name: "{{ packages }}"
    state: latest
  until: result is succeeded
  vars:
    packages:
      - ansible
      - python-psycopg2
      - python-setuptools
      - libselinux-python
      - setools-libs
      - yum-utils
      - sudo
      - acl

- name: Install ansible
  yum:
    name: "{{ packages }}"
    state: absent
  until: result is succeeded
  vars:
    packages:
      - erlang
      - socat
      - rabbitmq-server


