---

- name: Remove firewalld
  yum:
    name: firewalld
    state: absent

- name: Install ansible
  yum:
    name: "{{ packages }}"
    state: latest
  until: result is succeeded
  vars:
    packages:
      - ansible

- name: Install ansible
  yum:
    name: "{{ packages }}"
    state: absent
  until: result is succeeded
  vars:
    packages:
      - erlang
      - socat
      - rabbitmq-server


