---

- name: Download the terraform configuration files
  hosts: localhost
  connection: local
  vars:
    repository_url: https://github.com/techraving/tf-aws-ansible-tower.git
    base_directory: /tmp/terraform
    version: master
    ssh_user: ansible

  tasks:
  # - name: Create the destination base_directory
  #   file:
  #     path: "{{ base_directory }}"
  #     state: directory 

  # - name: Download the terraform config from git
  #   git:
  #     repo: "{{ repository_url }}"
  #     dest: "{{ base_directory }}"
  #     version: "{{ version }}"
      
  - name: Run the Terraform plans
    block:
      # - name: Run the templates for provisioning a virtual machine
      #   terraform:
      #     project_path: "{{ base_directory }}"
      #     state: present
      #     force_init: true
      #     variables_file: "{{ base_directory }}/aws_vars.tfvars"

      - name: Get status from Terraform
        command: terraform show -json
        register: terraform_result
        args:
          chdir: "{{ base_directory }}"

      - name: Add to tower_ui_haproxy node groups
        add_host:
          hostname: "{{ item }}"
          groups: 
            - tower_ui_haproxy
          ansible_user: "{{ ssh_user }}"
          ports:
            - 80
            - 443
        loop: "{{ terraform_result['stdout'] | get_group_instances('tower_ui_haproxy') | list }}"

      - name: Add to tower_ui node groups
        add_host:
          hostname: "{{ item }}"
          groups: 
            - tower_ui
          ansible_user: "{{ ssh_user }}"
          postgresql_username: 'ansible_tower'
          postgresql_password: 'Redhat@2019!'
          postgresql_database: 'tower'
          postgresql_root_password: 'smartvm'
          ports:
            - 80
            - 443
        loop: "{{ terraform_result['stdout'] | get_group_instances('tower_ui') | list }}"

      - name: Add to tower_db_haproxy node groups
        add_host:
          hostname: "{{ item }}"
          groups: 
            - tower_db_haproxy
          ansible_user: "{{ ssh_user }}"
          ports:
            - 5432
        loop: "{{ terraform_result['stdout'] | get_group_instances('tower_db_haproxy') | list }}"

      - name: Add to tower_db node groups
        add_host:
          hostname: "{{ (terraform_result['stdout'] | get_group_instances('tower_db') | list)[0] }}"
          groups: 
            - tower_db
          ansible_user: "{{ ssh_user }}"
          ports:
            - 5432
          pgsqlrep_role: master
          postgresql_username: 'ansible_tower'
          postgresql_password: 'Redhat@2019!'
          postgresql_database: 'tower'
          postgresql_root_password: 'smartvm'

      - name: Add to tower_db_replicas node groups
        add_host:
          hostname: "{{ item }}"
          groups: 
            - tower_db_replicas
          ansible_user: "{{ ssh_user }}"
          ports:
            - 5432
          pgsqlrep_role: replica
          postgresql_username: 'ansible_tower'
          postgresql_password: 'Redhat@2019!'
          postgresql_database: 'tower'
          postgresql_root_password: 'smartvm'
        loop: "{{ (terraform_result['stdout'] | get_group_instances('tower_db') | list)[1:] | list }}"

      # - name: waiting for tower_ui_haproxy servers to come back
      #   local_action: wait_for host={{ item }} port=22 state=started delay=30 timeout=240
      #   become: false
      #   loop: "{{ terraform_result['stdout'] | get_group_instances('tower_ui_haproxy') | list }}"

      # - name: waiting for tower_ui servers to come back
      #   local_action: wait_for host={{ item }} port=22 state=started delay=30 timeout=240
      #   become: false
      #   loop: "{{ terraform_result['stdout'] | get_group_instances('tower_ui') | list }}"

      # - name: waiting for tower_db_haproxy servers to come back
      #   local_action: wait_for host={{ item }} port=22 state=started delay=30 timeout=240
      #   become: false
      #   loop: "{{ terraform_result['stdout'] | get_group_instances('tower_db_haproxy') | list }}"

      # - name: waiting for tower_db servers to come back
      #   local_action: wait_for host={{ (terraform_result['stdout'] | get_group_instances('tower_db') | list)[0] }} port=22 state=started delay=30 timeout=240
      #   become: false

      # - name: waiting for tower_db_replicas servers to come back
      #   local_action: wait_for host={{ item }} port=22 state=started delay=30 timeout=240
      #   become: false
      #   loop: "{{ (terraform_result['stdout'] | get_group_instances('tower_db') | list)[1:] | list }}"

    rescue:
      - debug:
          msg: test
      # - name: Terraform destroy the install
      #   terraform:
      #     project_path: "{{ base_directory }}"
      #     state: absent
      #     variables_file: "{{ base_directory }}/aws_vars.tfvars"

      # - name: Delete the terraform destination base_directory
      #   file:
      #     path: "{{ base_directory }}"
      #     state: absent

# - name: subscribe the instances to 
#   hosts: tower_ui
#   become: true
#   vars:
#     rhel_username: skrutsinger
#     rhel_password: D4rkn3ss1t01!
#     rh_pool_ids:
#       - 8a85f99b6e417e2e016e6f0478444048
#     rh_repos:
#       - rhel-7-server-extras-rpms

#   tasks:
#   - name: Check for RedHat host
#     fail:
#       msg: "This role is only supported for Red Hat hosts"
#     when: ansible_os_family != 'RedHat'

#   - name: Check for rhel_username
#     fail:
#       msg: rhel_username env variable is required for this role.
#     when: rhel_username is not defined

#   - name: Check for rhel_password
#     fail:
#       msg: rhel_password env variable is required for this role.
#     when: rhel_password is not defined

#   - name: Install Red Hat Subscription manager
#     package:
#       name: subscription-manager
#       state: present
#     when: ansible_distribution == 'CentOS'

#   - name: Unregister
#     command: subscription-manager unregister
#     ignore_errors: true
#     changed_when: false

#   - name: Register RedHat Subscriptions
#     redhat_subscription:
#       state: present
#       username: "{{ rhel_username }}"
#       password: "{{ rhel_password }}"

#   - name: Subscribe Pools
#     command: "subscription-manager subscribe --pool {{ item }}"
#     with_items: "{{ rh_pool_ids }}"
#     retries: 3
#     delay: 2
#     register: result
#     ignore_errors: true
#     until: result is  succeeded
#     when: rh_pool_ids is defined

#   - name: Enable RedHat Repos
#     command: subscription-manager repos --enable {{ item }}
#     with_items: "{{ rh_repos }}"
#     retries: 3
#     delay: 2
#     register: result
#     until: result is succeeded
#     when: rh_repos is defined

# - name: Run the ansible playbook to provision instances
#   hosts: all
#   become: true

#   roles:
#     - role: provision

# - name: Install Postgresql Databases
#   hosts: tower_db, tower_db_replicas
#   become: true

#   roles:
#     - role: "postgres_install"

# - name: Replicate Postgresql Databases
#   hosts: tower_db, tower_db_replicas
#   become: true

#   roles:
#     - role: "postgres_replication"
#       when: groups['tower_db_replicas']|length > 0

# - name: Replicate Postgresql HAProxy
#   hosts: tower_db_haproxy
#   become: true

#   roles:
#     - role: "postgres_haproxy"

# - name: Prepare UI Servers
#   hosts: tower_ui
#   become: true

#   roles:
#     - role: "prepare_servers"

- name: Deploy .ssh files
  hosts: tower_ui
  become: true

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /root/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        mode: '0600'

- name: Install Ansible Tower
  hosts: tower_ui[0]
  become: true

  roles:
    - role: "tower_install"

# - name: Install Load Balancer for Ansible Tower UI
#   hosts: tower_ui_haproxy
#   become: true

#   roles:
#     - role: "tower_haproxy"
#       vars:
#         lb_groups_key: 'tower_ui'

# - name: Update ui servers to point to Postgresl Load Balancer
#   hosts: tower_ui
#   become: true

#   tasks:
#     - name: Update the postgres.py
#       lineinfile:
#         path: /etc/tower/conf.d/postgres.py
#         regexp: "'HOST': '{{ groups['tower_db'][0] }}',"
#         line: "'HOST': '{{ groups['tower_db_haproxy'][0] }}',"
#       when: groups['tower_db_haproxy']|length > 0

#     - name: Restart tower
#       command: ansible-tower-service restart
#       when: groups['tower_db_haproxy']|length > 0